spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/airort_plaground
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true

server:
  port: 8080